### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by enabokov**

### CODE REVIEW

**Comment by webknjaz** [comment]
Tests are failing + pinning versions in a library distribution is normally not a good idea.

**Comment by hellysmile** [comment]
@enabokov can You fix tests? seems they are failing due exact these versions matrix?

**Comment by enabokov** [comment]
@hellysmile yes, I'll fix them

**Comment by webknjaz** [comment]
What exactly are you fixing now? It looks like the PRs purpose changed.

**Comment by enabokov** [comment]
@webknjaz I am trying to fix tests. As far as I understand, there is a problem with docker. It doesn't expose proper ports.

**Comment by webknjaz** [comment]
If so, you probably need to pin the docker client library to some working version, because it likely worked earlier.

**Pull request closed without merging**
